### ISSUE TITLE
Erreur d'ouverture du fichier (Mac OS)

### ISSUE THREAD

**Issue by rphlmm** [LeMoineau/milireader2pdf#2]
Bonsoir,

Une fois que la commande: `python3 main.py` est lancée, je choisis l'option "Choisir un fichier" mais ça plante "The open file operation failed."

Voici ce qui m'arrive:

![https://i.imgur.com/BC90zeM.png](https://i.imgur.com/BC90zeM.png)

Que dois-je faire?
Merci

**Comment by LeMoineau** [comment]
Bonjour,
J'ai développé entre-temps une version beaucoup plus facile d'utilisation grâce aux extensions Chrome.
Voici le lien: https://github.com/LeMoineau/milireader2pdf-Extension 

Avec cette version, vous avez juste à cliquer sur le bouton "Générer le PDF" en étant sur la page Web où se trouve votre lecteur milibris-reader (journal par exemple) et l'extension fera son travail !

La seule difficulté réside en son installation puisque je n'ai pas de compte Google Developer certifié. 
Pour installer l'extension vous devez aller dans les paramètres de votre navigateur chrome puis dans le menu "Extensions" pour activer l'option "Mode développeur"
![image](https://user-images.githubusercontent.com/56643922/135835155-d242c15a-6e96-46b1-a040-f8b5ee7f7e98.png)


Une fois ce mode activé, vous aurez 3 nouvelles actions possibles: "Charger l'extension non empaquetée", "Empaqueter l'extension" et "Mettre à jour". 
![image](https://user-images.githubusercontent.com/56643922/135835331-d63e3d92-f923-4cca-bddd-bbfaa645b7ef.png)


Vous devez alors cliquer sur "Charger l'extension non empaquetée" puis sélectionner le dossier dans lequel vous avez téléchargé le projet "milibrisreader2pdf-Extension" (github) plus haut.
![image](https://user-images.githubusercontent.com/56643922/135836337-6ab364b3-8fe3-432b-a701-78796661f981.png)


Une icone d'oiseau devrait alors apparaitre pour confirmer que vous avez bien installé l'extension
![image](https://user-images.githubusercontent.com/56643922/135836493-960b9baa-3120-41ed-9f2d-3186ca652266.png)


Vous pouvez maintenant utiliser l'extension ! 
![Capture d’écran (178)_LI](https://user-images.githubusercontent.com/56643922/135836962-89914e73-daff-4bdd-83f3-2dc0bf7b4496.jpg)


puis
![image](https://user-images.githubusercontent.com/56643922/135837108-cd22a6bb-4f12-47f2-b073-25c0af4c0555.png)


Bonne journée et bonne utilisation
